# Generated by Django 5.2.4 on 2025-08-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_allotment_feestipendbond_seatmatrix_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllotmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=50)),
                ('ai_rank', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('quota', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('stipend_year1', models.CharField(max_length=50)),
                ('bond_years', models.CharField(max_length=50)),
                ('bond_penalty', models.CharField(max_length=50)),
                ('beds', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClosingRanksData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=255)),
                ('quota', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('fee', models.CharField(max_length=50)),
                ('stipend_year1', models.CharField(max_length=50)),
                ('bond_years', models.CharField(max_length=50)),
                ('bond_penalty', models.CharField(max_length=50)),
                ('beds', models.CharField(max_length=50)),
                ('cr_2023_1', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2023_2', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2023_3', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2023_4', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2023_5', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2024_1', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2024_2', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2024_3', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2024_4', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2024_5', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FeeStipendBondData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_type', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('quota', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('stipend_year1', models.CharField(max_length=50)),
                ('bond_years', models.CharField(max_length=50)),
                ('bond_penalty', models.CharField(max_length=50)),
                ('beds', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SeatMatrixData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.CharField(max_length=50)),
                ('quota', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=100)),
                ('institute', models.CharField(max_length=255)),
                ('course', models.CharField(max_length=255)),
                ('seats', models.CharField(max_length=50)),
                ('fee', models.CharField(max_length=50)),
                ('stipend_year1', models.CharField(max_length=50)),
                ('bond_years', models.CharField(max_length=50)),
                ('bond_penalty', models.CharField(max_length=50)),
                ('beds', models.CharField(max_length=50)),
                ('cr_2023_1', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2023_2', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2023_3', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2023_4', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2023_5', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2024_1', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2024_2', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2024_3', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2024_4', models.CharField(blank=True, max_length=50, null=True)),
                ('cr_2024_5', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
