# Generated by Django 5.2.4 on 2025-09-14 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_allotmentdata_closingranksdata_feestipendbonddata_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allotmentdata',
            name='bond_years',
            field=models.CharField(blank=True, null=True),
        ),
    ]
