# Generated by Django 5.2.4 on 2025-09-14 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_allotmentdata_bond_years'),
    ]

    operations = [
        migrations.AlterField(
            model_name='closingranksdata',
            name='bond_years',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='feestipendbonddata',
            name='bond_years',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seatmatrixdata',
            name='bond_penalty',
            field=models.CharField(blank=True, null=True),
        ),
    ]
