# Generated by Django 5.2.4 on 2026-06-10 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_customuser_gclid_customuser_landing_url_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UGAllotmentData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round', models.IntegerField()),
                ('ai_rank', models.IntegerField()),
                ('state', models.CharField(max_length=255)),
                ('institute', models.TextField()),
                ('course', models.CharField(max_length=255)),
                ('quota', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255)),
                ('fee', models.BigIntegerField(blank=True, null=True)),
                ('beds', models.IntegerField(blank=True, null=True)),
                ('bond_years', models.IntegerField(blank=True, null=True)),
                ('bond_penalty', models.BigIntegerField(blank=True, null=True)),
                ('stipend_year1', models.BigIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ai_rank'],
            },
        ),
    ]
